name: "Build Armbian"
on:
  workflow_dispatch:
jobs:
  build-armbian:
    runs-on: ubuntu-latest
    steps:
      - uses: Freedom0925/armbian-build@main
        name: "Build Armbian"
        with:
          armbian_token:         "${{ secrets.GITHUB_TOKEN }}"  # GitHub token
          armbian_release:       "trixie"              # userspace
          armbian_target:        "build"                        # build=image, kernel=kernel
          armbian_board:         "orangepi5-plus"               # build target
          armbian_kernel_branch: "vendor"           # legacy,vendor,current,edge
          armbian_ui:            "minimal"
          armbian_extensions:    "v4l2loopback-dkms,mesa-vpu"
